title: Mingyu Kim
# logo: /assets/img/profile_pic.png
logo: /assets/img/circle_pic.png
description: Incoming Assistant Professor in Electrical and Computer Engineering Department at Georgia Southern University
# show_downloads: true
theme: jekyll-theme-minimal
